### ISSUE TITLE
Incomplete / does not seem to work?

### ISSUE THREAD

**Issue by borismus** [chrisdmacrae/symlinks-obsidian#1]
Thanks for posting this! However this plugin doesn't seem to show up in the community plugins list, and I wasn't able to see it in the list of installed plugins when I manually installed as per your instructions.

**Comment by chrisdmacrae** [comment]
@borismus it is still pending on being added to the list, as the obsidian team may take this logic and just bake it into core.

However, if you clone it into your obsidian plugin folder, it should work.

However, the folder _may not_ be in the default `.obsidian` location. You may need to locate it, and then clone this repo into the `plugins` folder.

The end result should be something like:

```
.obsidian/
  plugins/
    symlinks-obsidian/
      data.json
      ...
```
